##
##  Makefile -- Build procedure for sample whoisd Apache module
##  Autogenerated via ``apxs -n whoisd -g''.
##

builddir=.
top_srcdir=~/apache.org/chroot
top_builddir=~/apache.org/chroot
CORBA_OBJS=whois-client.lo ccReg-common.lo  ccReg-stubs.lo
IDLOUT    = ccReg-common.c  ccReg-stubs.c  ccReg.h
ORBIT_IDL = orbit-idl-2

include ~/apache.org/chroot/build/special.mk

#   the used tools
APXS=apxs
APACHECTL=apachectl

#   additional defines, includes and libraries
DEFS=-DORBIT2=1
INCLUDES=-I/usr/include/orbit-2.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include
LIBS=-lORBitCosNaming-2 -lORBit-2 -lm -lgmodule-2.0 -ldl -lgthread-2.0 -lglib-2.0

#   the default target
all: local-shared-build

#   install the shared object file into Apache 
install: install-modules

$(CORBA_OBJS):  $(IDLOUT)

$(IDLOUT): ../cr/idl/ccReg.idl
	$(ORBIT_IDL) ../cr/idl/ccReg.idl

clean:
	rm -f $(IDLOUT)
